schema: './playground/schema.graphql'
documents:
  - './playground/app/pages/**/*.graphql'
  - './playground/app/components/**/*.graphql'
  - './playground/app/composables/**/*.graphql'
  - './playground/app/plugins/**/*.graphql'
